#!/usr/bin/env python3
from __future__ import print_function
from geniatagger import GeniaTagger, END_SEQUENCE
import socketserver
import argparse
import socket
import sys
import json


class TaggerTCPHandler(socketserver.StreamRequestHandler):

    def handle(self):
        for line in self.rfile:
            line = line.strip()
            if line:
                sent = str(line, 'utf-8')
                print(("\033[1;32m + \033[m"
                       "\033[1;33m{}:{} sent -> \033[m {}").format(self.client_address[0], self.client_address[1], sent))
                self.wfile.write(self.server.tagger.parse(sent, raw=True) + END_SEQUENCE)
                self.wfile.flush()


import fileinput
import shlex
import os


def argparser():
    parser = argparse.ArgumentParser(
        description=("GeniaTagger Server\n\n"
                     "$ geniatagger-server ~/tools/geniatagger-3.0.1/geniatagger -- -nt"),
        formatter_class=argparse.RawTextHelpFormatter,
        usage='''usage: geniatagger-server [-h] [-p PORT] [-a ADDRESS]
                          geniatagger [-- arguments ...]'''
    )

    parser.add_argument('-p', '--port', default=9595, type=int, help='port to listen on (default: %(default)s)')
    parser.add_argument('-a', '--address', default='localhost', type=str,
                        help='address to listen on (default: %(default)s)')
    parser.add_argument(
        'geniatagger', help='path to geniatagger binary program. (E.g. `~/tools/geniatagger-3.0.1/geniatagger\')')
    parser.add_argument(
        'arguments', help='geniatagger arguments. Add `--\' before arguments startwith `-\' (E.g. `-nt\'.)', nargs='*')
    return parser.parse_args()


def main():

    options = argparser()

    tagger_path = os.path.expanduser(options.geniatagger)
    print(('\033[32m *\033[m '
           'Running GeniaTagger with: \033[33m{} {}\033[m\n'
           '\033[32m * \033[m'
           'Listening on: \033[33m{}:{}\033[m\n').format(
               tagger_path, ' '.join(options.arguments), options.address, options.port))

    server = socketserver.TCPServer((options.address, options.port), TaggerTCPHandler)
    server.tagger = GeniaTagger(tagger_path, options.arguments)
    server.serve_forever()


if __name__ == '__main__':
    main()
